[package]
name = "rtnw"
version = "0.1.0"
authors = ["ishanjain28 <ishanjain28@gmail.com>"]
edition = "2018"

[features]
default = ["gui"]
gui = ["sdl2"]

[dependencies]
sdl2 = { version = "0.34.0", optional = true }
rand = { version = "0.8.3", features = ["small_rng"] }
rayon = "1.5.0"
